language: cpp
dist: trusty
sudo: false
matrix:
  include:
    - os: osx
      osx_image: xcode9.2
    # - os: linux
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #       packages:
    #         - g++ 7
    #   env:
    #     - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    # - os: linux
    #   addons:
    #     apt:
    #       sources:
    #         - llvm-toolchain-trusty-5.0
    #       packages:
    #         - clang-5.0
    #   env:
    #     - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
before_install:
  - eval "${MATRIX_EVAL}"
  - ${CXX} --version
install:
  - mkdir build;
    cd build;
  - cmake .. -DBUILD_CASCTESTS=on;
  - make;
script:
  - make test;
