language: cpp
dist: trusty
sudo: false
# addons:
#   apt:
#     sources:
#       - ubuntu-toolchain-r-test
#       - george-edison55-precise-backports
#     packages:
#       - clang
#       - doxygen
compiler:
  - clang
install:
  - mkdir build;
    cd build;
    cmake .. -DBUILD_CASCTESTS=on;
    make;
script:
  - make $TEST_TYPE;
