language: cpp
dist: trusty
sudo: false
addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
    packages:
      - clang-5.0
 env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
compiler:
  - clang
before_install:
  - eval "${MATRIX_EVAL}"
install:
  - mkdir build;
    cd build;
    cmake .. -DBUILD_CASCTESTS=on;
    make;
script:
  - make $TEST_TYPE;
