notifications:
  email: false

language: cpp
dist: trusty
sudo: false

# Blacklist
branches:
  only:
    - master
    - development
matrix:
  include:
    - os: osx
      osx_image: xcode
      before_install:
        - brew install doxygen --with-graphviz --withllvm
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
before_install:
  - eval "${MATRIX_EVAL}"
install:
  - mkdir build; cd build;
  - cmake ..;
  - make -j4;
script:
  - ctest -V
after_success:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      make docs
    fi;
deploy:
  provider: pages
  local-dir: build/html
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: master
    condition: $TRAVIS_OS_NAME == osx
