notifications:
  email: false

language: cpp
dist: trusty
sudo: false

# Blacklist
branches:
  only:
    - master

matrix:
  include:
    - os: osx
      osx_image: xcode9.3beta
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++ && BUILD_DOCS=1"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
before_install:
  - eval "${MATRIX_EVAL}"
install:
  - mkdir build; cd build;
  - cmake .. -DBUILD_CASCTESTS=on;
  - make -j4;
script:
  - ./bin/casctests;
after_success:
  - if [[ "$BUILD_DOCS" == "1" ]; then
      brew install doxygen;
      brew install graphviz;
      cmake ..;
      make casc_doc;
    fi;
deploy:
  edge:
    branch: v1.8.47
  provider: pages
  local-dir: build/html
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: master
    condition: "$BUILD_DOCS" == "1"
