language: cpp
dist: trusty
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - clang
      - cmake-data
      - cmake
compiler:
  - clang
install:
  - >-
    mkdir build;
    cmake .. $BUILD_FLAGS -DCOMPILER=$COMPILER
    make -j2
script:
  - make $TEST_TYPE;
