language: cpp
dist: trusty
sudo: false

# Blacklist
branches:
  only:
    - master

matrix:
  include:
    - os: osx
      osx_image: xcode9.3beta
    # - os: linux
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #       packages:
    #         - g++ 7
    #         - doxygen
    #         - doxygen-doc
    #         - graphviz
    #   env:
    #     - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    # - os: linux
    #   addons:
    #     apt:
    #       sources:
    #         - llvm-toolchain-trusty-5.0
    #       packages:
    #         - clang-5.0
    #   env:
    #     - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
before_install:
  - eval "${MATRIX_EVAL}"
  - ${CXX} --version
install:
  - mkdir build;
    cd build;
  - cmake .. -DBUILD_CASCTESTS=on;
  - make;
script:
  - ./bin/casctests;

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew install doxygen;
      cmake ..;
      make casc_docs;
    fi;
deploy:
  provider: pages
  local-dir: #TRAVIS_BUILD_DIR/build/html
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
